### ISSUE TITLE
Hardcoded https redirection

### ISSUE THREAD

**Issue by cameronmoreau** [thales-e-security/envoy#4]
We noticed that once an authcode is obtained, the app is redirected back to the `authentication_callback` url, except the [protocol is hardcoded](https://github.com/thales-e-security/envoy/blob/oidc/source/extensions/filters/http/oidc/oidc_filter.cc#L184) to `https`. We saw this as a small problem today since those on a development environment will have to setup a self-signed key.

A couple things were were thinking would be
1. `authentication_callback` could just be the full url? for example `http://localhost:10000/oidc/authenticate` or `https://acme.co/oidc/authenticate`?
2. `authentication_callback_protocol` could be one of `http` or `https`

What do you think, should this be configurable?

**Comment by nickrmc83** [comment]
I'm very reluctant to allow `http` to be specified as it's a potential security vulnerability as sensitive material is exchanged over that channel. In addition, and from the specificaition:

`When using this flow, the Redirection URI MUST NOT use the http scheme unless the Client is a native application, in which case it MAY use the http: scheme with localhost as the hostname.`

I'd not even want to allow `http://localhost` because editing `/etc/hosts` can allow `localhost` to alias to any address.

**Comment by peterhaochen47** [comment]
@nickrmc83 I see. Please close this issue. We looked at this after we filed the issue too. It seems like this is not as big of an issue as we thought, as the `authentication_callback` step is front-end as opposed to back-channel. So there's some hack we could do on the front-end to handle the SSL issue. Thanks!

**Comment by nickrmc83** [comment]
Marking as "wont-do"
