### ISSUE TITLE
Allow configurable scopes for the oidc filter

### ISSUE THREAD

**Issue by cameronmoreau** [thales-e-security/envoy#6]
We noticed that the [redirectToAuthenicationServer](https://github.com/thales-e-security/envoy/blob/oidc/source/extensions/filters/http/oidc/oidc_filter.cc#L241) function will hardcode `openid` and `email` as the value of the scope param.

Should we be able to make these scopes configurable? In addition, we think developers should be able to configure the scopes field as an empty array and envoy will omit the scope parameter when redirecting to AuthServer.

**Comment by nickrmc83** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest states `openid` must be specified so we should always make sure is present. We could allow further scopes to be requested as part of the config so that extra claims appear in the ID token. If the configuration contains an empty set of configurable scopes then just `openid` will be sent so that we comply with the specification always.

**Comment by nickrmc83** [comment]
Fixed by 7f6414ce9fb41561d8082d66895a77fb90a863ff
